### ISSUE TITLE
Error loading resource with ? in its location

### ISSUE THREAD

**Issue by dportoles** [BergWerkGIS/QGIS-CKAN-Browser#10]
When loading a resource with a ? in its location, CKAN-Browser raises an error:
Download error: invalid mode ('wb') or filename

**Comment by BergWerkGIS** [comment]
Can you point me to an example?

**Comment by dportoles** [comment]
http://sitar.aragon.es/datosdescarga/descarga.php?file=medioambiente/inagis_descargas/rednat_enp.shp.zip

You can reach it using http://opendata.aragon.es/catalogo/api/3 and searching for term "ENP"

**Comment by dportoles** [comment]
Maybe related:
These resource of (European Data Portal) raises same error
http://opendata.aragon.es/catalogo/data/espacios-naturales-protegidos-enp_rednat_enp/shp

It's the same shapefile but with other URL (without question mark). Maybe the problem are dashes?

You can reach it searching "enp aragon" and selecting item "Protected natural areas (protected areas)" => SHP

**Comment by BergWerkGIS** [comment]
@dportoles 
Thanks for the examples.

Problem is that the headers of the server response report the file name with quotes `"` and a semicolon `;` like this:

```
['Content-Disposition']: 	attachment; filename="rednat_enp.shp.zip";
```

So the generated local file path becomes:

```
path/to/cache-dir/"rednat_enp.shp.zip";
```

and this is not valid.

Will have to strip the quotes and the semicolon.
