### ISSUE TITLE
ProxySchemeUnknown error blocks service connection

### ISSUE THREAD

**Issue by mandsch** [BergWerkGIS/QGIS-CKAN-Browser#11]
Hi, 

installed the plugin from QGIS 2.14 on Win7 (v 0.2.9). I cannot connect to any CKAN server neither on the internet nor in our intranet. I get this error in the log:

URL: http://ckan.data.ktn.gv.at/api/3/
api request: http://ckan.data.ktn.gv.at/api/3/action/group_list?all_fields=true
Unerwarteter Fehler beim Request:  &lt; class 'CKANBrowser.request.packages.urllib3.exceptions.ProxySchemeUnknown' &gt;

I'm behind a proxy, but other internal and external services such as WxS or CSW work without problems.
In QGIS I have configured a HttpProxy in network settings.

Thanks, Michael

**Comment by BergWerkGIS** [comment]
Hi Michael,

parsing of proxy settings seems to be faulty.

Please help verify and change back to your original settings afterwards.

----

Run this in the Python console:
```python
from PyQt4.QtCore import QSettings
s = QSettings()
s.setValue("proxy/proxyUser", None)
s.setValue("proxy/proxyPassword", None )
```

Then change proxy settings:
*  Host: enter fully qualified proxy URL, e.g. `http://<PROXY_USER>:<PROXY_PWD>@<PROXY_IP>`
  * If your proxy doesn't need authentication, just `http://<PROXY_IP>`
* Port: leave as is
* User, Password: don't click or enter anything

Does CKAN Browser work now?

**Comment by mandsch** [comment]
Hi, 

thanks for your answer, unfortunately it didn't work, but changed sth.:

1) change proxy settings through python console
2) adapt ProxyHost settings through GUI/options/Network, putting username and pw in the host string:

2016-03-09T14:32:48	1	URL: http://ckan.data.ktn.gv.at/api/3/
2016-03-09T14:32:48	1	api request: http://ckan.data.ktn.gv.at/api/3/action/group_list?all_fields=true
2016-03-09T14:32:50	1	Unerwarteter Fehler beim Request: <class 'CKANBrowser.request.exceptions.ConnectionError'>

Any ideas?

**Comment by mandsch** [comment]
sorry, missing the error code:
`Unerwarteter Fehler beim Request: <class 'CKANBrowser.request.exceptions.ConnectionError'>`
