### ISSUE TITLE
invalid mode ('wb') or filename"

### ISSUE THREAD

**Issue by michikommader** [BergWerkGIS/QGIS-CKAN-Browser#13]
### Environment

PlugIn version: 0.3.2

PlugIn installed from:

- [x] http://plugins.qgis.org/
- [ ] ZIP from Github
- [ ] Built from source

OS: 

- [ ] Linux
- [x] Windows
- [ ] OSX

### Expected behavior

Correctly loaded WMS.

### Actual behavior

"invalid mode ('wb') or filename" when trying to load the WMS in QGIS.

### Steps to reproduce the behavior

* CKAN Server API URL: https://open.nrw/api/3
* Data set: NRW: Straßennetz Landesbetrieb Straßenbau NRW

Maybe related to #10?

**Comment by BergWerkGIS** [comment]
@michikommader 
Thanks for reporting.
Issue was similar to #10 but not quite :smirk:.

NRW WMS should be working now.

Also tried WFS - worked on Linux but unfortunately not on Windows.
On Windows I get: `Capabilties document is not valid: unexpected end of file`

![image](https://cloud.githubusercontent.com/assets/4549888/23822931/7c974038-0657-11e7-8807-52b5d5c70f1f.png)

I submitted the update to plugins.qgis.org.

If you don't want to wait till it comes available there you can download the ZIP and do a manual install:
https://github.com/BergWerkGIS/QGIS-CKAN-Browser/releases
