### ISSUE TITLE
WMS resource doesn't work

### ISSUE THREAD

**Issue by drnextgis** [BergWerkGIS/QGIS-CKAN-Browser#2]
400 Bad Request

**Comment by BergWerkGIS** [comment]
Have you tried the resource URL in your browser?
Does it work there?

**Comment by drnextgis** [comment]
Plugin shows Online Resource URL (without `REQUEST` parameter) and if open this URL in browser you of course will get 400 HTTP error.

**Comment by BergWerkGIS** [comment]
> Plugin shows Online Resource URL (without `REQUEST` parameter)

The plugin shows the URL that was obtained from the CKAN Server.
If the URL misses some parameters it's most likely that the entry on the CKAN server that is faulty.

**Comment by drnextgis** [comment]
It is clear that  plugin shows the URL from the CKAN Server. But in this case (WMS, WFS services) resource URL is not direct URL to data but it only base part of this URL, the rest part (GET-parameters or POST payload) have to be defined by client application. I guess that in case of OWS services plugin should use already existed connections or open dialog window to create them.

**Comment by BergWerkGIS** [comment]
> I guess that in case of OWS services plugin should use already existed connections or open dialog window to create them.

Yes, that's exactly what the plugin does:

* if the URL provided by the server is correct
* if the URL gets correctly identified as WMS resource
* if the URL (Capabilites) can be downloaded

How about you post the CKAN URL (does `test connection` in the settings work?)  and the name of the data set you are trying to load?
Then we can take a look!

**Comment by drnextgis** [comment]
CKAN URL: http://78.46.100.76/opendata

**Comment by ndkv** [comment]
The OWS endpoints and their parameters are a [source of great confusion](https://github.com/openstate/CKAN-Link-Checker/issues/1). Some catalogs indeed list only the base URL while others include e.g. `request=GetCapabilities`. Some serve WMS/WFS from separate endpoints while others serve both from `/ows`. Developing robust consumers of OWS endpoints is therefore quite a challenge.

@drnextgis Your WMSs are offered without parameters. Accessing e.g. http://78.46.100.76/opendata_ngw/api/resource/507/wms gives a 400, indeed. 

@BergWerkGIS I might be wrong (or reading the wrong file) but it seems that you are [looking for `getcapabilities` in the URL](https://github.com/BergWerkGIS/QGIS-CKAN-Browser/blob/b22065f4fc3ffc00583be025221ff7a332e1f9a7/CKAN-Browser/ckanconnector.py#L175-L183) to determine whether you're dealing with an OWS resource? MIght this be causing the malfunction in this case?

**Comment by BergWerkGIS** [comment]
@ndkv yes, looking for the capabilities URL

> CKAN URL: http://78.46.100.76/opendata

@drnextgis that's the URL of the web page, you need the URL of the API.

The API URL is: http://78.46.100.76/opendata/api/3/

With that it works as expected:

![image](https://cloud.githubusercontent.com/assets/4549888/12655693/73b38aec-c5fa-11e5-9f41-3a28c3c87391.png)


To work with this plugin CKAN instance would have to return:

http://78.46.100.76/opendata_ngw/api/resource/567/wms?service=WMS&request=GetCapabilities

**Comment by drnextgis** [comment]
Thanks for quick response. But I think it is not common way to identify WMS resource using request=GetCapabilities and plugin should check mandatary parameters (SERVICE, WMS) and if they is omitted it should add them while making request.

**Comment by BergWerkGIS** [comment]
> But I think it is not common way to identify WMS resource using `request=GetCapabilities`

I tend to disagree.
What's the first thing you do with an unknown WMS?
You ask it for its Capabilities and then continue from there on.
So why not expect to get that instead of fiddling with the URL?
So the data provider can for instance already provide his preferred `VERSION` too.

Other way round, why not:
**WMS** should check mandatary parameters (`SERVICE`, `WMS`) and if they are omitted it should add them while _getting_ request.


Nevertheless I've created an issue to further investigate: https://github.com/BergWerkGIS/QGIS-CKAN-Browser/issues/7
