### ISSUE TITLE
Insecure redirect

### ISSUE THREAD

**Issue by geraldo** [BergWerkGIS/QGIS-CKAN-Browser#32]
### Environment

PlugIn version: 0.4.0

PlugIn installed from: http://plugins.qgis.org/

OS: Linux

### Expected behavior

Download data from redirected URL

### Actual behavior

`Network error #11: Insecure redirect`

### Steps to reproduce the behavior

* CKAN Server API URL: https://opendata-ajuntament.barcelona.cat/data/api/3/
* Data set: [List of education equipments in the city of Barcelona](https://opendata-ajuntament.barcelona.cat/data/en/dataset/equipament-educacio)

Resource URL is successfully found at https://opendata-ajuntament.barcelona.cat/data/dataset/f36b60f2-9541-4d08-b0f9-b0a9313fab3d/resource/29d9ff10-6892-4f16-9012-d5c4997857e7/download but gets redirected to http://www.bcn.cat/tercerlloc/files/llista-equipaments/opendatabcn_llista-equipaments_educacio-js.json

Where does error `Network error #11: Insecure redirect` come from? Is it because of redirection from https to http or is it because the actual resource is located on a different domain? What would the institution have to do to make their CKAN server work with your plugin?

**Comment by wilhelmberg** [comment]
@geraldo the error stems from [QNetworkReply::error()](https://doc.qt.io/qt-6/qnetworkreply.html#error).

The reason for the error is the downgrade of the connection from HTTPS to HTTP. 
[QNetworkReply::InsecureRedirectError](https://doc.qt.io/qt-6/qnetworkreply.html#NetworkError-enum):
> while following redirects, the network access API detected a redirect from a encrypted protocol (https) to an unencrypted one (http).

Enabling HTTPS on bcn.cat would most likely solve this.

**Comment by geraldo** [comment]
@wilhelmberg Thanks for your quick response. I'm in contact with Open Data BCN and hope they can change https to http on bcn.es

As this is expected behaviour so closing for now.
